// Code generated by MockGen. DO NOT EDIT.
// Source: blacklist_interface.go
//
// Generated by this command:
//
//	mockgen -source=blacklist_interface.go -destination ../mock/repository/blacklist_interface.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"
	domain "wfs/backend/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockBlackListInterface is a mock of BlackListInterface interface.
type MockBlackListInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBlackListInterfaceMockRecorder
	isgomock struct{}
}

// MockBlackListInterfaceMockRecorder is the mock recorder for MockBlackListInterface.
type MockBlackListInterfaceMockRecorder struct {
	mock *MockBlackListInterface
}

// NewMockBlackListInterface creates a new mock instance.
func NewMockBlackListInterface(ctrl *gomock.Controller) *MockBlackListInterface {
	mock := &MockBlackListInterface{ctrl: ctrl}
	mock.recorder = &MockBlackListInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlackListInterface) EXPECT() *MockBlackListInterfaceMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockBlackListInterface) Load() (*domain.BlackList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*domain.BlackList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockBlackListInterfaceMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockBlackListInterface)(nil).Load))
}

// Save mocks base method.
func (m *MockBlackListInterface) Save(data domain.BlackList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockBlackListInterfaceMockRecorder) Save(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBlackListInterface)(nil).Save), data)
}
