// Code generated by MockGen. DO NOT EDIT.
// Source: file_store_interface.go
//
// Generated by this command:
//
//	mockgen -source=file_store_interface.go -destination ../mock/repository/file_store_interface.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"
	data "wfs/backend/data"

	gomock "go.uber.org/mock/gomock"
)

// MockFileStoreInterface is a mock of FileStoreInterface interface.
type MockFileStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFileStoreInterfaceMockRecorder
	isgomock struct{}
}

// MockFileStoreInterfaceMockRecorder is the mock recorder for MockFileStoreInterface.
type MockFileStoreInterfaceMockRecorder struct {
	mock *MockFileStoreInterface
}

// NewMockFileStoreInterface creates a new mock instance.
func NewMockFileStoreInterface(ctrl *gomock.Controller) *MockFileStoreInterface {
	mock := &MockFileStoreInterface{ctrl: ctrl}
	mock.recorder = &MockFileStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStoreInterface) EXPECT() *MockFileStoreInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFileStoreInterface) Delete(key data.FileStorePath) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFileStoreInterfaceMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFileStoreInterface)(nil).Delete), key)
}

// Files mocks base method.
func (m *MockFileStoreInterface) Files(childPath string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Files", childPath)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Files indicates an expected call of Files.
func (mr *MockFileStoreInterfaceMockRecorder) Files(childPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Files", reflect.TypeOf((*MockFileStoreInterface)(nil).Files), childPath)
}

// Get mocks base method.
func (m *MockFileStoreInterface) Get(key data.FileStorePath) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFileStoreInterfaceMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFileStoreInterface)(nil).Get), key)
}

// Put mocks base method.
func (m *MockFileStoreInterface) Put(key data.FileStorePath, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockFileStoreInterfaceMockRecorder) Put(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockFileStoreInterface)(nil).Put), key, value)
}
