// Code generated by MockGen. DO NOT EDIT.
// Source: user_config_interface.go
//
// Generated by this command:
//
//	mockgen -source=user_config_interface.go -destination ../mock/repository/user_config_interface.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"
	domain "wfs/backend/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockUserConfigInterface is a mock of UserConfigInterface interface.
type MockUserConfigInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserConfigInterfaceMockRecorder
	isgomock struct{}
}

// MockUserConfigInterfaceMockRecorder is the mock recorder for MockUserConfigInterface.
type MockUserConfigInterfaceMockRecorder struct {
	mock *MockUserConfigInterface
}

// NewMockUserConfigInterface creates a new mock instance.
func NewMockUserConfigInterface(ctrl *gomock.Controller) *MockUserConfigInterface {
	mock := &MockUserConfigInterface{ctrl: ctrl}
	mock.recorder = &MockUserConfigInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserConfigInterface) EXPECT() *MockUserConfigInterfaceMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockUserConfigInterface) Load() (*domain.UserConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*domain.UserConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockUserConfigInterfaceMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockUserConfigInterface)(nil).Load))
}

// Save mocks base method.
func (m *MockUserConfigInterface) Save(data domain.UserConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserConfigInterfaceMockRecorder) Save(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserConfigInterface)(nil).Save), data)
}
