// Code generated by MockGen. DO NOT EDIT.
// Source: warship_fetcher_interface.go
//
// Generated by this command:
//
//	mockgen -source=warship_fetcher_interface.go -destination ../mock/repository/warship_fetcher_interface.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"
	model "wfs/backend/domain/model"

	gomock "go.uber.org/mock/gomock"
)

// MockWarshipFetcherInterface is a mock of WarshipFetcherInterface interface.
type MockWarshipFetcherInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWarshipFetcherInterfaceMockRecorder
	isgomock struct{}
}

// MockWarshipFetcherInterfaceMockRecorder is the mock recorder for MockWarshipFetcherInterface.
type MockWarshipFetcherInterfaceMockRecorder struct {
	mock *MockWarshipFetcherInterface
}

// NewMockWarshipFetcherInterface creates a new mock instance.
func NewMockWarshipFetcherInterface(ctrl *gomock.Controller) *MockWarshipFetcherInterface {
	mock := &MockWarshipFetcherInterface{ctrl: ctrl}
	mock.recorder = &MockWarshipFetcherInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarshipFetcherInterface) EXPECT() *MockWarshipFetcherInterfaceMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockWarshipFetcherInterface) Fetch() (model.Warships, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch")
	ret0, _ := ret[0].(model.Warships)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockWarshipFetcherInterfaceMockRecorder) Fetch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockWarshipFetcherInterface)(nil).Fetch))
}
