// Code generated by MockGen. DO NOT EDIT.
// Source: adapter.go
//
// Generated by this command:
//
//	mockgen -source=adapter.go -destination ../mock/adapter.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	data "wfs/backend/data"

	gomock "go.uber.org/mock/gomock"
)

// MockWails is a mock of Wails interface.
type MockWails struct {
	ctrl     *gomock.Controller
	recorder *MockWailsMockRecorder
	isgomock struct{}
}

// MockWailsMockRecorder is the mock recorder for MockWails.
type MockWailsMockRecorder struct {
	mock *MockWails
}

// NewMockWails creates a new mock instance.
func NewMockWails(ctrl *gomock.Controller) *MockWails {
	mock := &MockWails{ctrl: ctrl}
	mock.recorder = &MockWailsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWails) EXPECT() *MockWailsMockRecorder {
	return m.recorder
}

// EmitEvent mocks base method.
func (m *MockWails) EmitEvent(ctx context.Context, eventName string, optionalData ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, eventName}
	for _, a := range optionalData {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "EmitEvent", varargs...)
}

// EmitEvent indicates an expected call of EmitEvent.
func (mr *MockWailsMockRecorder) EmitEvent(ctx, eventName any, optionalData ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, eventName}, optionalData...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitEvent", reflect.TypeOf((*MockWails)(nil).EmitEvent), varargs...)
}

// OpenDirectoryDialog mocks base method.
func (m *MockWails) OpenDirectoryDialog(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenDirectoryDialog", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenDirectoryDialog indicates an expected call of OpenDirectoryDialog.
func (mr *MockWailsMockRecorder) OpenDirectoryDialog(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenDirectoryDialog", reflect.TypeOf((*MockWails)(nil).OpenDirectoryDialog), ctx)
}

// MockCacheStore is a mock of CacheStore interface.
type MockCacheStore struct {
	ctrl     *gomock.Controller
	recorder *MockCacheStoreMockRecorder
	isgomock struct{}
}

// MockCacheStoreMockRecorder is the mock recorder for MockCacheStore.
type MockCacheStoreMockRecorder struct {
	mock *MockCacheStore
}

// NewMockCacheStore creates a new mock instance.
func NewMockCacheStore(ctrl *gomock.Controller) *MockCacheStore {
	mock := &MockCacheStore{ctrl: ctrl}
	mock.recorder = &MockCacheStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheStore) EXPECT() *MockCacheStoreMockRecorder {
	return m.recorder
}

// BattleArenas mocks base method.
func (m *MockCacheStore) BattleArenas() (map[int]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BattleArenas")
	ret0, _ := ret[0].(map[int]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BattleArenas indicates an expected call of BattleArenas.
func (mr *MockCacheStoreMockRecorder) BattleArenas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BattleArenas", reflect.TypeOf((*MockCacheStore)(nil).BattleArenas))
}

// BattleTypes mocks base method.
func (m *MockCacheStore) BattleTypes() (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BattleTypes")
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BattleTypes indicates an expected call of BattleTypes.
func (mr *MockCacheStoreMockRecorder) BattleTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BattleTypes", reflect.TypeOf((*MockCacheStore)(nil).BattleTypes))
}

// OwnIGN mocks base method.
func (m *MockCacheStore) OwnIGN() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnIGN")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OwnIGN indicates an expected call of OwnIGN.
func (mr *MockCacheStoreMockRecorder) OwnIGN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnIGN", reflect.TypeOf((*MockCacheStore)(nil).OwnIGN))
}

// SetBattleArenas mocks base method.
func (m *MockCacheStore) SetBattleArenas(arg0 map[int]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBattleArenas", arg0)
}

// SetBattleArenas indicates an expected call of SetBattleArenas.
func (mr *MockCacheStoreMockRecorder) SetBattleArenas(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBattleArenas", reflect.TypeOf((*MockCacheStore)(nil).SetBattleArenas), arg0)
}

// SetBattleTypes mocks base method.
func (m *MockCacheStore) SetBattleTypes(arg0 map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBattleTypes", arg0)
}

// SetBattleTypes indicates an expected call of SetBattleTypes.
func (mr *MockCacheStoreMockRecorder) SetBattleTypes(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBattleTypes", reflect.TypeOf((*MockCacheStore)(nil).SetBattleTypes), arg0)
}

// SetOwnIGN mocks base method.
func (m *MockCacheStore) SetOwnIGN(ign string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOwnIGN", ign)
}

// SetOwnIGN indicates an expected call of SetOwnIGN.
func (mr *MockCacheStoreMockRecorder) SetOwnIGN(ign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOwnIGN", reflect.TypeOf((*MockCacheStore)(nil).SetOwnIGN), ign)
}

// SetWarships mocks base method.
func (m *MockCacheStore) SetWarships(arg0 data.Warships) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWarships", arg0)
}

// SetWarships indicates an expected call of SetWarships.
func (mr *MockCacheStoreMockRecorder) SetWarships(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWarships", reflect.TypeOf((*MockCacheStore)(nil).SetWarships), arg0)
}

// Warships mocks base method.
func (m *MockCacheStore) Warships() (data.Warships, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Warships")
	ret0, _ := ret[0].(data.Warships)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Warships indicates an expected call of Warships.
func (mr *MockCacheStoreMockRecorder) Warships() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warships", reflect.TypeOf((*MockCacheStore)(nil).Warships))
}

// MockPrefStore is a mock of PrefStore interface.
type MockPrefStore struct {
	ctrl     *gomock.Controller
	recorder *MockPrefStoreMockRecorder
	isgomock struct{}
}

// MockPrefStoreMockRecorder is the mock recorder for MockPrefStore.
type MockPrefStoreMockRecorder struct {
	mock *MockPrefStore
}

// NewMockPrefStore creates a new mock instance.
func NewMockPrefStore(ctrl *gomock.Controller) *MockPrefStore {
	mock := &MockPrefStore{ctrl: ctrl}
	mock.recorder = &MockPrefStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrefStore) EXPECT() *MockPrefStoreMockRecorder {
	return m.recorder
}

// Pref mocks base method.
func (m *MockPrefStore) Pref() (data.Pref, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pref")
	ret0, _ := ret[0].(data.Pref)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pref indicates an expected call of Pref.
func (mr *MockPrefStoreMockRecorder) Pref() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pref", reflect.TypeOf((*MockPrefStore)(nil).Pref))
}

// SetPref mocks base method.
func (m *MockPrefStore) SetPref(arg0 data.Pref) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPref", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPref indicates an expected call of SetPref.
func (mr *MockPrefStoreMockRecorder) SetPref(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPref", reflect.TypeOf((*MockPrefStore)(nil).SetPref), arg0)
}

// MockReplayReader is a mock of ReplayReader interface.
type MockReplayReader struct {
	ctrl     *gomock.Controller
	recorder *MockReplayReaderMockRecorder
	isgomock struct{}
}

// MockReplayReaderMockRecorder is the mock recorder for MockReplayReader.
type MockReplayReaderMockRecorder struct {
	mock *MockReplayReader
}

// NewMockReplayReader creates a new mock instance.
func NewMockReplayReader(ctrl *gomock.Controller) *MockReplayReader {
	mock := &MockReplayReader{ctrl: ctrl}
	mock.recorder = &MockReplayReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplayReader) EXPECT() *MockReplayReaderMockRecorder {
	return m.recorder
}

// TempArenaInfo mocks base method.
func (m *MockReplayReader) TempArenaInfo(installPath string) (data.TempArenaInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TempArenaInfo", installPath)
	ret0, _ := ret[0].(data.TempArenaInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TempArenaInfo indicates an expected call of TempArenaInfo.
func (mr *MockReplayReaderMockRecorder) TempArenaInfo(installPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TempArenaInfo", reflect.TypeOf((*MockReplayReader)(nil).TempArenaInfo), installPath)
}

// MockClanClient is a mock of ClanClient interface.
type MockClanClient struct {
	ctrl     *gomock.Controller
	recorder *MockClanClientMockRecorder
	isgomock struct{}
}

// MockClanClientMockRecorder is the mock recorder for MockClanClient.
type MockClanClientMockRecorder struct {
	mock *MockClanClient
}

// NewMockClanClient creates a new mock instance.
func NewMockClanClient(ctrl *gomock.Controller) *MockClanClient {
	mock := &MockClanClient{ctrl: ctrl}
	mock.recorder = &MockClanClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClanClient) EXPECT() *MockClanClientMockRecorder {
	return m.recorder
}

// ClanAutoComplete mocks base method.
func (m *MockClanClient) ClanAutoComplete(ctx context.Context, search string) (data.ClanAutocomplete, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClanAutoComplete", ctx, search)
	ret0, _ := ret[0].(data.ClanAutocomplete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClanAutoComplete indicates an expected call of ClanAutoComplete.
func (mr *MockClanClientMockRecorder) ClanAutoComplete(ctx, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClanAutoComplete", reflect.TypeOf((*MockClanClient)(nil).ClanAutoComplete), ctx, search)
}

// MockDiscordClient is a mock of DiscordClient interface.
type MockDiscordClient struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordClientMockRecorder
	isgomock struct{}
}

// MockDiscordClientMockRecorder is the mock recorder for MockDiscordClient.
type MockDiscordClientMockRecorder struct {
	mock *MockDiscordClient
}

// NewMockDiscordClient creates a new mock instance.
func NewMockDiscordClient(ctrl *gomock.Controller) *MockDiscordClient {
	mock := &MockDiscordClient{ctrl: ctrl}
	mock.recorder = &MockDiscordClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordClient) EXPECT() *MockDiscordClientMockRecorder {
	return m.recorder
}

// Comment mocks base method.
func (m *MockDiscordClient) Comment(ctx context.Context, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Comment", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Comment indicates an expected call of Comment.
func (mr *MockDiscordClientMockRecorder) Comment(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Comment", reflect.TypeOf((*MockDiscordClient)(nil).Comment), ctx, message)
}

// MockGithubClient is a mock of GithubClient interface.
type MockGithubClient struct {
	ctrl     *gomock.Controller
	recorder *MockGithubClientMockRecorder
	isgomock struct{}
}

// MockGithubClientMockRecorder is the mock recorder for MockGithubClient.
type MockGithubClientMockRecorder struct {
	mock *MockGithubClient
}

// NewMockGithubClient creates a new mock instance.
func NewMockGithubClient(ctrl *gomock.Controller) *MockGithubClient {
	mock := &MockGithubClient{ctrl: ctrl}
	mock.recorder = &MockGithubClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGithubClient) EXPECT() *MockGithubClientMockRecorder {
	return m.recorder
}

// LatestRelease mocks base method.
func (m *MockGithubClient) LatestRelease(ctx context.Context) (data.GHLatestRelease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestRelease", ctx)
	ret0, _ := ret[0].(data.GHLatestRelease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestRelease indicates an expected call of LatestRelease.
func (mr *MockGithubClientMockRecorder) LatestRelease(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestRelease", reflect.TypeOf((*MockGithubClient)(nil).LatestRelease), ctx)
}

// MockNumbersClient is a mock of NumbersClient interface.
type MockNumbersClient struct {
	ctrl     *gomock.Controller
	recorder *MockNumbersClientMockRecorder
	isgomock struct{}
}

// MockNumbersClientMockRecorder is the mock recorder for MockNumbersClient.
type MockNumbersClientMockRecorder struct {
	mock *MockNumbersClient
}

// NewMockNumbersClient creates a new mock instance.
func NewMockNumbersClient(ctrl *gomock.Controller) *MockNumbersClient {
	mock := &MockNumbersClient{ctrl: ctrl}
	mock.recorder = &MockNumbersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNumbersClient) EXPECT() *MockNumbersClientMockRecorder {
	return m.recorder
}

// ExpectedStats mocks base method.
func (m *MockNumbersClient) ExpectedStats(ctx context.Context) (data.NSExpectedStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectedStats", ctx)
	ret0, _ := ret[0].(data.NSExpectedStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpectedStats indicates an expected call of ExpectedStats.
func (mr *MockNumbersClientMockRecorder) ExpectedStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectedStats", reflect.TypeOf((*MockNumbersClient)(nil).ExpectedStats), ctx)
}

// MockWargamingClient is a mock of WargamingClient interface.
type MockWargamingClient struct {
	ctrl     *gomock.Controller
	recorder *MockWargamingClientMockRecorder
	isgomock struct{}
}

// MockWargamingClientMockRecorder is the mock recorder for MockWargamingClient.
type MockWargamingClientMockRecorder struct {
	mock *MockWargamingClient
}

// NewMockWargamingClient creates a new mock instance.
func NewMockWargamingClient(ctrl *gomock.Controller) *MockWargamingClient {
	mock := &MockWargamingClient{ctrl: ctrl}
	mock.recorder = &MockWargamingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWargamingClient) EXPECT() *MockWargamingClientMockRecorder {
	return m.recorder
}

// AccountInfo mocks base method.
func (m *MockWargamingClient) AccountInfo(ctx context.Context, accountIDs []data.AccountID) (data.WGAccountInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountInfo", ctx, accountIDs)
	ret0, _ := ret[0].(data.WGAccountInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountInfo indicates an expected call of AccountInfo.
func (mr *MockWargamingClientMockRecorder) AccountInfo(ctx, accountIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountInfo", reflect.TypeOf((*MockWargamingClient)(nil).AccountInfo), ctx, accountIDs)
}

// AccountList mocks base method.
func (m *MockWargamingClient) AccountList(ctx context.Context, accountNames []string) (data.WGAccountList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountList", ctx, accountNames)
	ret0, _ := ret[0].(data.WGAccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountList indicates an expected call of AccountList.
func (mr *MockWargamingClientMockRecorder) AccountList(ctx, accountNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountList", reflect.TypeOf((*MockWargamingClient)(nil).AccountList), ctx, accountNames)
}

// BattleArenas mocks base method.
func (m *MockWargamingClient) BattleArenas(ctx context.Context) (data.WGBattleArenas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BattleArenas", ctx)
	ret0, _ := ret[0].(data.WGBattleArenas)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BattleArenas indicates an expected call of BattleArenas.
func (mr *MockWargamingClientMockRecorder) BattleArenas(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BattleArenas", reflect.TypeOf((*MockWargamingClient)(nil).BattleArenas), ctx)
}

// BattleTypes mocks base method.
func (m *MockWargamingClient) BattleTypes(ctx context.Context) (data.WGBattleTypes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BattleTypes", ctx)
	ret0, _ := ret[0].(data.WGBattleTypes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BattleTypes indicates an expected call of BattleTypes.
func (mr *MockWargamingClientMockRecorder) BattleTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BattleTypes", reflect.TypeOf((*MockWargamingClient)(nil).BattleTypes), ctx)
}

// ClansAccountInfo mocks base method.
func (m *MockWargamingClient) ClansAccountInfo(ctx context.Context, accountIDs []data.AccountID) (data.WGClansAccountInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClansAccountInfo", ctx, accountIDs)
	ret0, _ := ret[0].(data.WGClansAccountInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClansAccountInfo indicates an expected call of ClansAccountInfo.
func (mr *MockWargamingClientMockRecorder) ClansAccountInfo(ctx, accountIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClansAccountInfo", reflect.TypeOf((*MockWargamingClient)(nil).ClansAccountInfo), ctx, accountIDs)
}

// ClansInfo mocks base method.
func (m *MockWargamingClient) ClansInfo(ctx context.Context, clanIDs []data.ClanID) (data.WGClansInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClansInfo", ctx, clanIDs)
	ret0, _ := ret[0].(data.WGClansInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClansInfo indicates an expected call of ClansInfo.
func (mr *MockWargamingClientMockRecorder) ClansInfo(ctx, clanIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClansInfo", reflect.TypeOf((*MockWargamingClient)(nil).ClansInfo), ctx, clanIDs)
}

// EncycShips mocks base method.
func (m *MockWargamingClient) EncycShips(ctx context.Context, pageNo int) (data.WGEncycShips, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncycShips", ctx, pageNo)
	ret0, _ := ret[0].(data.WGEncycShips)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncycShips indicates an expected call of EncycShips.
func (mr *MockWargamingClientMockRecorder) EncycShips(ctx, pageNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncycShips", reflect.TypeOf((*MockWargamingClient)(nil).EncycShips), ctx, pageNo)
}

// ShipsBadges mocks base method.
func (m *MockWargamingClient) ShipsBadges(ctx context.Context, accountID data.AccountID) (data.WGShipsBadges, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShipsBadges", ctx, accountID)
	ret0, _ := ret[0].(data.WGShipsBadges)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShipsBadges indicates an expected call of ShipsBadges.
func (mr *MockWargamingClientMockRecorder) ShipsBadges(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShipsBadges", reflect.TypeOf((*MockWargamingClient)(nil).ShipsBadges), ctx, accountID)
}

// ShipsStats mocks base method.
func (m *MockWargamingClient) ShipsStats(ctx context.Context, accountID data.AccountID) (data.WGShipsStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShipsStats", ctx, accountID)
	ret0, _ := ret[0].(data.WGShipsStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShipsStats indicates an expected call of ShipsStats.
func (mr *MockWargamingClientMockRecorder) ShipsStats(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShipsStats", reflect.TypeOf((*MockWargamingClient)(nil).ShipsStats), ctx, accountID)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(message string, contexts map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", message, contexts)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(message, contexts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), message, contexts)
}

// Error mocks base method.
func (m *MockLogger) Error(err error, contexts map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", err, contexts)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(err, contexts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), err, contexts)
}

// Info mocks base method.
func (m *MockLogger) Info(message string, contexts map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", message, contexts)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(message, contexts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), message, contexts)
}

// SetOwnIGN mocks base method.
func (m *MockLogger) SetOwnIGN(ownIGN string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOwnIGN", ownIGN)
}

// SetOwnIGN indicates an expected call of SetOwnIGN.
func (mr *MockLoggerMockRecorder) SetOwnIGN(ownIGN any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOwnIGN", reflect.TypeOf((*MockLogger)(nil).SetOwnIGN), ownIGN)
}
