version: "2"

# https://golangci-lint.run/usage/linters/
linters:
  default: all
  disable:
    - wrapcheck
    - forbidigo
    - funlen
    - wsl # deprecated
    - wsl_v5
    - exhaustruct
    - ireturn
    - tagliatelle
    - varnamelen
    - noctx
    - nlreturn
    - testpackage
    - asciicheck
    - interfacebloat
    - depguard
    - gosmopolitan
    - revive
    - predeclared
    - mnd
    - bodyclose
    - godox
    - containedctx
    - contextcheck
    - embeddedstructfieldcheck
    - noinlineerr
    - godoclint
  exclusions:
    paths:
      - _test\.go
  settings:
    gosec:
      excludes:
        - G301
        - G302
        - G304
        - G306
