# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - tenv # Deprecated
    - wrapcheck
    - forbidigo
    - funlen
    - wsl
    - exhaustruct
    - ireturn
    - tagliatelle
    - varnamelen
    - noctx
    - nlreturn
    - gci # Conflict goimports
    - goimports # Conflict goimports
    - testpackage
    - asciicheck
    - interfacebloat
    - depguard
    - gosmopolitan
    - revive
    - predeclared
    - mnd
    - testifylint
