# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - scopelint # Deprecated
    - golint # Deprecated
    - nosnakecase # Deprecated
    - ifshort # Deprecated
    - maligned # Deprecated
    - varcheck # Deprecated
    - interfacer # Deprecated
    - deadcode # Deprecated
    - exhaustivestruct # Deprecated
    - structcheck # Deprecated
    - wrapcheck
    - forbidigo
    - funlen
    - wsl
    - exhaustruct
    - gomnd
    - ireturn
    - tagliatelle
    - varnamelen
    - noctx
    - nlreturn
    - gci # Conflict goimports
    - goimports # Conflict goimports
    - testpackage
    - asciicheck
    - interfacebloat
    - depguard
    - gosmopolitan
