# https://taskfile.dev

version: "3"

vars:
  NPM: npm --prefix ./frontend
  APP_NAME: wows-fast-stats
  VERSION: 1.0.0-alpha.1

tasks:
  setup:
    desc: setup project
    cmds:
      - for:
          - github.com/wailsapp/wails/v2/cmd/wails@v2.10.2
          - github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
          - go.uber.org/mock/mockgen@latest
        cmd: go install {{.ITEM}}
  gen-mock:
    desc: generate mocks
    cmds:
      - rm -rf internal/mock
      - go generate ./...
  lint:
    desc: lint
    cmds:
      - golangci-lint run
      - "{{.NPM}} run check"
      - "{{.NPM}} run lint"
  fmt:
    desc: format
    cmds:
      - golangci-lint run --fix
      - go fmt
      - "{{.NPM}} run fmt"
      - "{{.NPM}} run fmt-svelte"
  test:
    desc: unit testing
    cmds:
      - go clean -testcache
      - go test -cover ./...
      # - "{{.NPM}} run test"
  dev:
    desc: run app in development mode
    cmds:
      - wails dev -ldflags="-X main.appName={{.APP_NAME}} -X main.semver={{.VERSION}} -X main.env=dev"
  build:
    desc: build
    deps: [test]
    cmds:
      - wails build -ldflags="-X main.appName={{.APP_NAME}} -X main.semver={{.VERSION}} -X main.env=prod" -platform windows/amd64 -o {{.APP_NAME}}-{{.VERSION}}.exe -trimpath -webview2 embed
  chbtl:
    desc: change battle
    vars:
      TEST_REPLAY_PATH: ./test_install_dir/replays
      TEMP_ARENA_INFO: tempArenaInfo.json
    cmds:
      - cp {{.TEST_REPLAY_PATH}}/$(ls {{.TEST_REPLAY_PATH}} | grep -v {{.TEMP_ARENA_INFO}} | fzf) {{.TEST_REPLAY_PATH}}/{{.TEMP_ARENA_INFO}}
  clean:
    desc: clean project
    cmds:
      - for:
          - config/
          - cache/
          - temp_arena_info/
          - screenshot/
          - persistent_data/
          - user_data/
        cmd: rm -rf {{.ITEM}}
  update:
    desc: update dependencies
    cmds:
      - go get -u
      - "{{.NPM}} update"
