// Code generated by "stringer -type=AppErrorName"; DO NOT EDIT.

package apperr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HTTPRequest-0]
	_ = x[WargamingAPITemporaryUnavaillalble-1]
	_ = x[WargamingAPIError-2]
	_ = x[NumbersAPIParse-3]
	_ = x[ReadFile-4]
	_ = x[WriteFile-5]
	_ = x[DecodeBase64-6]
	_ = x[DiscordAPIError-7]
	_ = x[ShowDialog-8]
	_ = x[UserCanceled-9]
	_ = x[OpenDirectory-10]
	_ = x[FrontendError-11]
}

const _AppErrorName_name = "HTTPRequestWargamingAPITemporaryUnavaillalbleWargamingAPIErrorNumbersAPIParseReadFileWriteFileDecodeBase64DiscordAPIErrorShowDialogUserCanceledOpenDirectoryFrontendError"

var _AppErrorName_index = [...]uint8{0, 11, 45, 62, 77, 85, 94, 106, 121, 131, 143, 156, 169}

func (i AppErrorName) String() string {
	if i < 0 || i >= AppErrorName(len(_AppErrorName_index)-1) {
		return "AppErrorName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AppErrorName_name[_AppErrorName_index[i]:_AppErrorName_index[i+1]]
}
