// Code generated by MockGen. DO NOT EDIT.
// Source: battle_meta_fetcher.go
//
// Generated by this command:
//
//	mockgen -source=battle_meta_fetcher.go -destination ../mock/repository/battle_meta_fetcher.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"
	model "wfs/backend/domain/model"

	gomock "go.uber.org/mock/gomock"
)

// MockBattleMetaFetcher is a mock of BattleMetaFetcher interface.
type MockBattleMetaFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockBattleMetaFetcherMockRecorder
	isgomock struct{}
}

// MockBattleMetaFetcherMockRecorder is the mock recorder for MockBattleMetaFetcher.
type MockBattleMetaFetcherMockRecorder struct {
	mock *MockBattleMetaFetcher
}

// NewMockBattleMetaFetcher creates a new mock instance.
func NewMockBattleMetaFetcher(ctrl *gomock.Controller) *MockBattleMetaFetcher {
	mock := &MockBattleMetaFetcher{ctrl: ctrl}
	mock.recorder = &MockBattleMetaFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBattleMetaFetcher) EXPECT() *MockBattleMetaFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockBattleMetaFetcher) Fetch() (model.BattleMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch")
	ret0, _ := ret[0].(model.BattleMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockBattleMetaFetcherMockRecorder) Fetch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockBattleMetaFetcher)(nil).Fetch))
}
