// Code generated by MockGen. DO NOT EDIT.
// Source: clan_fetcher.go
//
// Generated by this command:
//
//	mockgen -source=clan_fetcher.go -destination ../mock/repository/clan_fetcher.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"
	model "wfs/backend/domain/model"

	gomock "go.uber.org/mock/gomock"
)

// MockClanFetcher is a mock of ClanFetcher interface.
type MockClanFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockClanFetcherMockRecorder
	isgomock struct{}
}

// MockClanFetcherMockRecorder is the mock recorder for MockClanFetcher.
type MockClanFetcherMockRecorder struct {
	mock *MockClanFetcher
}

// NewMockClanFetcher creates a new mock instance.
func NewMockClanFetcher(ctrl *gomock.Controller) *MockClanFetcher {
	mock := &MockClanFetcher{ctrl: ctrl}
	mock.recorder = &MockClanFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClanFetcher) EXPECT() *MockClanFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockClanFetcher) Fetch(accountIDs []int) (model.Clans, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", accountIDs)
	ret0, _ := ret[0].(model.Clans)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockClanFetcherMockRecorder) Fetch(accountIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockClanFetcher)(nil).Fetch), accountIDs)
}
