// Code generated by MockGen. DO NOT EDIT.
// Source: clan_fetcher_interface.go
//
// Generated by this command:
//
//	mockgen -source=clan_fetcher_interface.go -destination ../mock/repository/clan_fetcher_interface.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"
	model "wfs/backend/domain/model"

	gomock "go.uber.org/mock/gomock"
)

// MockClanFetcherInterface is a mock of ClanFetcherInterface interface.
type MockClanFetcherInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClanFetcherInterfaceMockRecorder
	isgomock struct{}
}

// MockClanFetcherInterfaceMockRecorder is the mock recorder for MockClanFetcherInterface.
type MockClanFetcherInterfaceMockRecorder struct {
	mock *MockClanFetcherInterface
}

// NewMockClanFetcherInterface creates a new mock instance.
func NewMockClanFetcherInterface(ctrl *gomock.Controller) *MockClanFetcherInterface {
	mock := &MockClanFetcherInterface{ctrl: ctrl}
	mock.recorder = &MockClanFetcherInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClanFetcherInterface) EXPECT() *MockClanFetcherInterfaceMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockClanFetcherInterface) Fetch(accountIDs []int) (model.Clans, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", accountIDs)
	ret0, _ := ret[0].(model.Clans)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockClanFetcherInterfaceMockRecorder) Fetch(accountIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockClanFetcherInterface)(nil).Fetch), accountIDs)
}
