// Code generated by MockGen. DO NOT EDIT.
// Source: raw_stat_fetcher_interface.go
//
// Generated by this command:
//
//	mockgen -source=raw_stat_fetcher_interface.go -destination ../mock/repository/raw_stat_fetcher_interface.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"
	model "wfs/backend/domain/model"

	gomock "go.uber.org/mock/gomock"
)

// MockRawStatFetcherInterface is a mock of RawStatFetcherInterface interface.
type MockRawStatFetcherInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRawStatFetcherInterfaceMockRecorder
	isgomock struct{}
}

// MockRawStatFetcherInterfaceMockRecorder is the mock recorder for MockRawStatFetcherInterface.
type MockRawStatFetcherInterfaceMockRecorder struct {
	mock *MockRawStatFetcherInterface
}

// NewMockRawStatFetcherInterface creates a new mock instance.
func NewMockRawStatFetcherInterface(ctrl *gomock.Controller) *MockRawStatFetcherInterface {
	mock := &MockRawStatFetcherInterface{ctrl: ctrl}
	mock.recorder = &MockRawStatFetcherInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRawStatFetcherInterface) EXPECT() *MockRawStatFetcherInterfaceMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockRawStatFetcherInterface) Fetch(accountIDs []int) (model.RawStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", accountIDs)
	ret0, _ := ret[0].(model.RawStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockRawStatFetcherInterfaceMockRecorder) Fetch(accountIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockRawStatFetcherInterface)(nil).Fetch), accountIDs)
}
