// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	domain "wfs/backend/domain"

	mock "github.com/stretchr/testify/mock"
)

// GithubInterface is an autogenerated mock type for the GithubInterface type
type GithubInterface struct {
	mock.Mock
}

// LatestRelease provides a mock function with given fields:
func (_m *GithubInterface) LatestRelease() (domain.GHLatestRelease, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LatestRelease")
	}

	var r0 domain.GHLatestRelease
	var r1 error
	if rf, ok := ret.Get(0).(func() (domain.GHLatestRelease, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() domain.GHLatestRelease); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.GHLatestRelease)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGithubInterface creates a new instance of GithubInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGithubInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GithubInterface {
	mock := &GithubInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
