// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	domain "wfs/backend/domain"

	mock "github.com/stretchr/testify/mock"
)

// LocalFileInterface is an autogenerated mock type for the LocalFileInterface type
type LocalFileInterface struct {
	mock.Mock
}

// SaveScreenshot provides a mock function with given fields: path, base64Data
func (_m *LocalFileInterface) SaveScreenshot(path string, base64Data string) error {
	ret := _m.Called(path, base64Data)

	if len(ret) == 0 {
		panic("no return value specified for SaveScreenshot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(path, base64Data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveTempArenaInfo provides a mock function with given fields: tempArenaInfo
func (_m *LocalFileInterface) SaveTempArenaInfo(tempArenaInfo domain.TempArenaInfo) error {
	ret := _m.Called(tempArenaInfo)

	if len(ret) == 0 {
		panic("no return value specified for SaveTempArenaInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.TempArenaInfo) error); ok {
		r0 = rf(tempArenaInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TempArenaInfo provides a mock function with given fields: installPath
func (_m *LocalFileInterface) TempArenaInfo(installPath string) (domain.TempArenaInfo, error) {
	ret := _m.Called(installPath)

	if len(ret) == 0 {
		panic("no return value specified for TempArenaInfo")
	}

	var r0 domain.TempArenaInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (domain.TempArenaInfo, error)); ok {
		return rf(installPath)
	}
	if rf, ok := ret.Get(0).(func(string) domain.TempArenaInfo); ok {
		r0 = rf(installPath)
	} else {
		r0 = ret.Get(0).(domain.TempArenaInfo)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(installPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLocalFileInterface creates a new instance of LocalFileInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocalFileInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocalFileInterface {
	mock := &LocalFileInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
