// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LoggerInterface is an autogenerated mock type for the LoggerInterface type
type LoggerInterface struct {
	mock.Mock
}

// Debug provides a mock function with given fields: message, contexts
func (_m *LoggerInterface) Debug(message string, contexts map[string]string) {
	_m.Called(message, contexts)
}

// Error provides a mock function with given fields: err, contexts
func (_m *LoggerInterface) Error(err error, contexts map[string]string) {
	_m.Called(err, contexts)
}

// Info provides a mock function with given fields: message, contexts
func (_m *LoggerInterface) Info(message string, contexts map[string]string) {
	_m.Called(message, contexts)
}

// Init provides a mock function with given fields: appCtx
func (_m *LoggerInterface) Init(appCtx context.Context) {
	_m.Called(appCtx)
}

// Warn provides a mock function with given fields: err, contexts
func (_m *LoggerInterface) Warn(err error, contexts map[string]string) {
	_m.Called(err, contexts)
}

// NewLoggerInterface creates a new instance of LoggerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerInterface {
	mock := &LoggerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
