// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	model "wfs/backend/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// NumbersInterface is an autogenerated mock type for the NumbersInterface type
type NumbersInterface struct {
	mock.Mock
}

// ExpectedStats provides a mock function with given fields:
func (_m *NumbersInterface) ExpectedStats() (model.ExpectedStats, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExpectedStats")
	}

	var r0 model.ExpectedStats
	var r1 error
	if rf, ok := ret.Get(0).(func() (model.ExpectedStats, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() model.ExpectedStats); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.ExpectedStats)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNumbersInterface creates a new instance of NumbersInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNumbersInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *NumbersInterface {
	mock := &NumbersInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
