// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReportInterface is an autogenerated mock type for the ReportInterface type
type ReportInterface struct {
	mock.Mock
}

// Send provides a mock function with given fields: message, content
func (_m *ReportInterface) Send(message string, content error) {
	_m.Called(message, content)
}

// NewReportInterface creates a new instance of ReportInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportInterface {
	mock := &ReportInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
