// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	model "wfs/backend/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// UnregisteredInterface is an autogenerated mock type for the UnregisteredInterface type
type UnregisteredInterface struct {
	mock.Mock
}

// Warship provides a mock function with given fields:
func (_m *UnregisteredInterface) Warship() (model.Warships, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Warship")
	}

	var r0 model.Warships
	var r1 error
	if rf, ok := ret.Get(0).(func() (model.Warships, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() model.Warships); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Warships)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUnregisteredInterface creates a new instance of UnregisteredInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnregisteredInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnregisteredInterface {
	mock := &UnregisteredInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
