// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentVersion() {
  return window['go']['controller']['Controller']['CurrentVersion']();
}

export function EmptyBattle() {
  return window['go']['controller']['Controller']['EmptyBattle']();
}

export function GetUserConfig() {
  return window['go']['controller']['Controller']['GetUserConfig']();
}

export function NewVersion() {
  return window['go']['controller']['Controller']['NewVersion']();
}

export function SaveUserConfig(arg1) {
  return window['go']['controller']['Controller']['SaveUserConfig'](arg1);
}

export function ShowMessageDialog(arg1) {
  return window['go']['controller']['Controller']['ShowMessageDialog'](arg1);
}

export function StartPollingMatch() {
  return window['go']['controller']['Controller']['StartPollingMatch']();
}

export function TrySaveInstallPath() {
  return window['go']['controller']['Controller']['TrySaveInstallPath']();
}
