// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source=api.go -destination ../mock/github/api.go -package github
//

// Package github is a generated GoMock package.
package github

import (
	reflect "reflect"
	github "wfs/backend2/infra/github"

	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// FetchLatestRelease mocks base method.
func (m *MockAPI) FetchLatestRelease() (github.LatestRelease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLatestRelease")
	ret0, _ := ret[0].(github.LatestRelease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLatestRelease indicates an expected call of FetchLatestRelease.
func (mr *MockAPIMockRecorder) FetchLatestRelease() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLatestRelease", reflect.TypeOf((*MockAPI)(nil).FetchLatestRelease))
}
