// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function CurrentVersion():Promise<string>;

export function EmptyBattle():Promise<data.Battle>;

export function LoadPref():Promise<data.Pref>;

export function NewVersion():Promise<data.NewVersion>;

export function Prefetch():Promise<void>;

export function SavePref(arg1:data.Pref):Promise<void>;

export function ShowMessageDialog(arg1:string):Promise<void>;

export function StartPollingMatch():Promise<void>;

export function TrySaveInstallPath():Promise<boolean>;
