// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentVersion() {
  return window['go']['main']['App']['CurrentVersion']();
}

export function FetchBattle(arg1) {
  return window['go']['main']['App']['FetchBattle'](arg1);
}

export function LoadDisplayPref() {
  return window['go']['main']['App']['LoadDisplayPref']();
}

export function LoadGameClientPath() {
  return window['go']['main']['App']['LoadGameClientPath']();
}

export function NewVersion() {
  return window['go']['main']['App']['NewVersion']();
}

export function Prefetch() {
  return window['go']['main']['App']['Prefetch']();
}

export function SaveDisplayPref(arg1) {
  return window['go']['main']['App']['SaveDisplayPref'](arg1);
}

export function SelectGameClientPath() {
  return window['go']['main']['App']['SelectGameClientPath']();
}

export function ShowMessageDialog(arg1) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1);
}

export function StartPollingMatch() {
  return window['go']['main']['App']['StartPollingMatch']();
}
