// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExcludePlayerID(arg1) {
  return window['go']['main']['App']['AddExcludePlayerID'](arg1);
}

export function AlertPatterns() {
  return window['go']['main']['App']['AlertPatterns']();
}

export function AlertPlayers() {
  return window['go']['main']['App']['AlertPlayers']();
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplyUserConfig(arg1) {
  return window['go']['main']['App']['ApplyUserConfig'](arg1);
}

export function AutoScreenshot(arg1, arg2) {
  return window['go']['main']['App']['AutoScreenshot'](arg1, arg2);
}

export function Battle() {
  return window['go']['main']['App']['Battle']();
}

export function ExcludePlayerIDs() {
  return window['go']['main']['App']['ExcludePlayerIDs']();
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function ManualScreenshot(arg1, arg2) {
  return window['go']['main']['App']['ManualScreenshot'](arg1, arg2);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function Ready() {
  return window['go']['main']['App']['Ready']();
}

export function RemoveAlertPlayer(arg1) {
  return window['go']['main']['App']['RemoveAlertPlayer'](arg1);
}

export function RemoveExcludePlayerID(arg1) {
  return window['go']['main']['App']['RemoveExcludePlayerID'](arg1);
}

export function SearchPlayer(arg1) {
  return window['go']['main']['App']['SearchPlayer'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpdateAlertPlayer(arg1) {
  return window['go']['main']['App']['UpdateAlertPlayer'](arg1);
}

export function UserConfig() {
  return window['go']['main']['App']['UserConfig']();
}
