// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vo} from '../models';

export function ApplyConfig(arg1:vo.UserConfig):Promise<vo.UserConfig>;

export function GetBattle():Promise<vo.Battle>;

export function GetConfig():Promise<vo.UserConfig>;

export function GetTempArenaInfoHash():Promise<string>;

export function SaveScreenshot(arg1:string,arg2:string):Promise<void>;

export function SaveScreenshotWithDialog(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;
