// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1) {
  return window['go']['main']['App']['Debug'](arg1);
}

export function Load() {
  return window['go']['main']['App']['Load']();
}
