// Code generated by MockGen. DO NOT EDIT.
// Source: cache_store.go
//
// Generated by this command:
//
//	mockgen -source=cache_store.go -destination ../mock/cache_store.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	data "wfs/internal/data"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheStore is a mock of CacheStore interface.
type MockCacheStore struct {
	ctrl     *gomock.Controller
	recorder *MockCacheStoreMockRecorder
	isgomock struct{}
}

// MockCacheStoreMockRecorder is the mock recorder for MockCacheStore.
type MockCacheStoreMockRecorder struct {
	mock *MockCacheStore
}

// NewMockCacheStore creates a new mock instance.
func NewMockCacheStore(ctrl *gomock.Controller) *MockCacheStore {
	mock := &MockCacheStore{ctrl: ctrl}
	mock.recorder = &MockCacheStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheStore) EXPECT() *MockCacheStoreMockRecorder {
	return m.recorder
}

// BattleArenas mocks base method.
func (m *MockCacheStore) BattleArenas() (map[int]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BattleArenas")
	ret0, _ := ret[0].(map[int]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BattleArenas indicates an expected call of BattleArenas.
func (mr *MockCacheStoreMockRecorder) BattleArenas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BattleArenas", reflect.TypeOf((*MockCacheStore)(nil).BattleArenas))
}

// BattleTypes mocks base method.
func (m *MockCacheStore) BattleTypes() (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BattleTypes")
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BattleTypes indicates an expected call of BattleTypes.
func (mr *MockCacheStoreMockRecorder) BattleTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BattleTypes", reflect.TypeOf((*MockCacheStore)(nil).BattleTypes))
}

// OwnIGN mocks base method.
func (m *MockCacheStore) OwnIGN() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnIGN")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OwnIGN indicates an expected call of OwnIGN.
func (mr *MockCacheStoreMockRecorder) OwnIGN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnIGN", reflect.TypeOf((*MockCacheStore)(nil).OwnIGN))
}

// SetBattleArenas mocks base method.
func (m *MockCacheStore) SetBattleArenas(arg0 map[int]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBattleArenas", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBattleArenas indicates an expected call of SetBattleArenas.
func (mr *MockCacheStoreMockRecorder) SetBattleArenas(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBattleArenas", reflect.TypeOf((*MockCacheStore)(nil).SetBattleArenas), arg0)
}

// SetBattleTypes mocks base method.
func (m *MockCacheStore) SetBattleTypes(arg0 map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBattleTypes", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBattleTypes indicates an expected call of SetBattleTypes.
func (mr *MockCacheStoreMockRecorder) SetBattleTypes(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBattleTypes", reflect.TypeOf((*MockCacheStore)(nil).SetBattleTypes), arg0)
}

// SetOwnIGN mocks base method.
func (m *MockCacheStore) SetOwnIGN(ign string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOwnIGN", ign)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOwnIGN indicates an expected call of SetOwnIGN.
func (mr *MockCacheStoreMockRecorder) SetOwnIGN(ign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOwnIGN", reflect.TypeOf((*MockCacheStore)(nil).SetOwnIGN), ign)
}

// SetWarships mocks base method.
func (m *MockCacheStore) SetWarships(arg0 data.Warships) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWarships", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWarships indicates an expected call of SetWarships.
func (mr *MockCacheStoreMockRecorder) SetWarships(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWarships", reflect.TypeOf((*MockCacheStore)(nil).SetWarships), arg0)
}

// Warships mocks base method.
func (m *MockCacheStore) Warships() (data.Warships, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Warships")
	ret0, _ := ret[0].(data.Warships)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Warships indicates an expected call of Warships.
func (mr *MockCacheStoreMockRecorder) Warships() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warships", reflect.TypeOf((*MockCacheStore)(nil).Warships))
}
