// Code generated by MockGen. DO NOT EDIT.
// Source: clan_api_client.go
//
// Generated by this command:
//
//	mockgen -source=clan_api_client.go -destination ../mock/clan_api_client.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	data "wfs/internal/data"

	gomock "go.uber.org/mock/gomock"
)

// MockClanApiClient is a mock of ClanApiClient interface.
type MockClanApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockClanApiClientMockRecorder
	isgomock struct{}
}

// MockClanApiClientMockRecorder is the mock recorder for MockClanApiClient.
type MockClanApiClientMockRecorder struct {
	mock *MockClanApiClient
}

// NewMockClanApiClient creates a new mock instance.
func NewMockClanApiClient(ctrl *gomock.Controller) *MockClanApiClient {
	mock := &MockClanApiClient{ctrl: ctrl}
	mock.recorder = &MockClanApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClanApiClient) EXPECT() *MockClanApiClientMockRecorder {
	return m.recorder
}

// ClanAutoComplete mocks base method.
func (m *MockClanApiClient) ClanAutoComplete(search string) (data.ClanAutocomplete, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClanAutoComplete", search)
	ret0, _ := ret[0].(data.ClanAutocomplete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClanAutoComplete indicates an expected call of ClanAutoComplete.
func (mr *MockClanApiClientMockRecorder) ClanAutoComplete(search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClanAutoComplete", reflect.TypeOf((*MockClanApiClient)(nil).ClanAutoComplete), search)
}
