// Code generated by MockGen. DO NOT EDIT.
// Source: config_store.go
//
// Generated by this command:
//
//	mockgen -source=config_store.go -destination ../mock/config_store.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	data "wfs/internal/data"

	gomock "go.uber.org/mock/gomock"
)

// MockConfigStore is a mock of ConfigStore interface.
type MockConfigStore struct {
	ctrl     *gomock.Controller
	recorder *MockConfigStoreMockRecorder
	isgomock struct{}
}

// MockConfigStoreMockRecorder is the mock recorder for MockConfigStore.
type MockConfigStoreMockRecorder struct {
	mock *MockConfigStore
}

// NewMockConfigStore creates a new mock instance.
func NewMockConfigStore(ctrl *gomock.Controller) *MockConfigStore {
	mock := &MockConfigStore{ctrl: ctrl}
	mock.recorder = &MockConfigStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigStore) EXPECT() *MockConfigStoreMockRecorder {
	return m.recorder
}

// SetUserConfig mocks base method.
func (m *MockConfigStore) SetUserConfig(arg0 data.UserConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserConfig indicates an expected call of SetUserConfig.
func (mr *MockConfigStoreMockRecorder) SetUserConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserConfig", reflect.TypeOf((*MockConfigStore)(nil).SetUserConfig), arg0)
}

// UserConfig mocks base method.
func (m *MockConfigStore) UserConfig() (data.UserConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfig")
	ret0, _ := ret[0].(data.UserConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserConfig indicates an expected call of UserConfig.
func (mr *MockConfigStoreMockRecorder) UserConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfig", reflect.TypeOf((*MockConfigStore)(nil).UserConfig))
}
