// Code generated by MockGen. DO NOT EDIT.
// Source: discord_api_client.go
//
// Generated by this command:
//
//	mockgen -source=discord_api_client.go -destination ../mock/discord_api_client.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDiscordApiClient is a mock of DiscordApiClient interface.
type MockDiscordApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordApiClientMockRecorder
	isgomock struct{}
}

// MockDiscordApiClientMockRecorder is the mock recorder for MockDiscordApiClient.
type MockDiscordApiClientMockRecorder struct {
	mock *MockDiscordApiClient
}

// NewMockDiscordApiClient creates a new mock instance.
func NewMockDiscordApiClient(ctrl *gomock.Controller) *MockDiscordApiClient {
	mock := &MockDiscordApiClient{ctrl: ctrl}
	mock.recorder = &MockDiscordApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordApiClient) EXPECT() *MockDiscordApiClientMockRecorder {
	return m.recorder
}

// Comment mocks base method.
func (m *MockDiscordApiClient) Comment(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Comment", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Comment indicates an expected call of Comment.
func (mr *MockDiscordApiClientMockRecorder) Comment(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Comment", reflect.TypeOf((*MockDiscordApiClient)(nil).Comment), message)
}
