// Code generated by MockGen. DO NOT EDIT.
// Source: github_api_client.go
//
// Generated by this command:
//
//	mockgen -source=github_api_client.go -destination ../mock/github_api_client.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	data "wfs/internal/data"

	gomock "go.uber.org/mock/gomock"
)

// MockGithubApiClient is a mock of GithubApiClient interface.
type MockGithubApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockGithubApiClientMockRecorder
	isgomock struct{}
}

// MockGithubApiClientMockRecorder is the mock recorder for MockGithubApiClient.
type MockGithubApiClientMockRecorder struct {
	mock *MockGithubApiClient
}

// NewMockGithubApiClient creates a new mock instance.
func NewMockGithubApiClient(ctrl *gomock.Controller) *MockGithubApiClient {
	mock := &MockGithubApiClient{ctrl: ctrl}
	mock.recorder = &MockGithubApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGithubApiClient) EXPECT() *MockGithubApiClientMockRecorder {
	return m.recorder
}

// LatestRelease mocks base method.
func (m *MockGithubApiClient) LatestRelease() (data.GHLatestRelease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestRelease")
	ret0, _ := ret[0].(data.GHLatestRelease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestRelease indicates an expected call of LatestRelease.
func (mr *MockGithubApiClientMockRecorder) LatestRelease() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestRelease", reflect.TypeOf((*MockGithubApiClient)(nil).LatestRelease))
}
