// Code generated by MockGen. DO NOT EDIT.
// Source: local_file_interface.go
//
// Generated by this command:
//
//	mockgen -source=local_file_interface.go -destination ../mock/local_file_interface.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	data "wfs/internal/data"

	gomock "go.uber.org/mock/gomock"
)

// MockLocalFileInterface is a mock of LocalFileInterface interface.
type MockLocalFileInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLocalFileInterfaceMockRecorder
	isgomock struct{}
}

// MockLocalFileInterfaceMockRecorder is the mock recorder for MockLocalFileInterface.
type MockLocalFileInterfaceMockRecorder struct {
	mock *MockLocalFileInterface
}

// NewMockLocalFileInterface creates a new mock instance.
func NewMockLocalFileInterface(ctrl *gomock.Controller) *MockLocalFileInterface {
	mock := &MockLocalFileInterface{ctrl: ctrl}
	mock.recorder = &MockLocalFileInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalFileInterface) EXPECT() *MockLocalFileInterfaceMockRecorder {
	return m.recorder
}

// TempArenaInfo mocks base method.
func (m *MockLocalFileInterface) TempArenaInfo(installPath string) (data.TempArenaInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TempArenaInfo", installPath)
	ret0, _ := ret[0].(data.TempArenaInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TempArenaInfo indicates an expected call of TempArenaInfo.
func (mr *MockLocalFileInterfaceMockRecorder) TempArenaInfo(installPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TempArenaInfo", reflect.TypeOf((*MockLocalFileInterface)(nil).TempArenaInfo), installPath)
}
