// Code generated by MockGen. DO NOT EDIT.
// Source: local_storage.go
//
// Generated by this command:
//
//	mockgen -source=local_storage.go -destination ../mock/local_storage.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	data "wfs/internal/data"

	gomock "go.uber.org/mock/gomock"
)

// MockLocalStorage is a mock of LocalStorage interface.
type MockLocalStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLocalStorageMockRecorder
	isgomock struct{}
}

// MockLocalStorageMockRecorder is the mock recorder for MockLocalStorage.
type MockLocalStorageMockRecorder struct {
	mock *MockLocalStorage
}

// NewMockLocalStorage creates a new mock instance.
func NewMockLocalStorage(ctrl *gomock.Controller) *MockLocalStorage {
	mock := &MockLocalStorage{ctrl: ctrl}
	mock.recorder = &MockLocalStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalStorage) EXPECT() *MockLocalStorageMockRecorder {
	return m.recorder
}

// ExpectedStats mocks base method.
func (m *MockLocalStorage) ExpectedStats() (data.NSExpectedStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectedStats")
	ret0, _ := ret[0].(data.NSExpectedStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpectedStats indicates an expected call of ExpectedStats.
func (mr *MockLocalStorageMockRecorder) ExpectedStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectedStats", reflect.TypeOf((*MockLocalStorage)(nil).ExpectedStats))
}

// OwnIGN mocks base method.
func (m *MockLocalStorage) OwnIGN() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnIGN")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OwnIGN indicates an expected call of OwnIGN.
func (mr *MockLocalStorageMockRecorder) OwnIGN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnIGN", reflect.TypeOf((*MockLocalStorage)(nil).OwnIGN))
}

// SetExpectedStats mocks base method.
func (m *MockLocalStorage) SetExpectedStats(arg0 data.NSExpectedStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExpectedStats", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetExpectedStats indicates an expected call of SetExpectedStats.
func (mr *MockLocalStorageMockRecorder) SetExpectedStats(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExpectedStats", reflect.TypeOf((*MockLocalStorage)(nil).SetExpectedStats), arg0)
}

// SetOwnIGN mocks base method.
func (m *MockLocalStorage) SetOwnIGN(ign string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOwnIGN", ign)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOwnIGN indicates an expected call of SetOwnIGN.
func (mr *MockLocalStorageMockRecorder) SetOwnIGN(ign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOwnIGN", reflect.TypeOf((*MockLocalStorage)(nil).SetOwnIGN), ign)
}

// SetUserConfig mocks base method.
func (m *MockLocalStorage) SetUserConfig(arg0 data.UserConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserConfig indicates an expected call of SetUserConfig.
func (mr *MockLocalStorageMockRecorder) SetUserConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserConfig", reflect.TypeOf((*MockLocalStorage)(nil).SetUserConfig), arg0)
}

// TempArenaInfo mocks base method.
func (m *MockLocalStorage) TempArenaInfo(installPath string) (data.TempArenaInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TempArenaInfo", installPath)
	ret0, _ := ret[0].(data.TempArenaInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TempArenaInfo indicates an expected call of TempArenaInfo.
func (mr *MockLocalStorageMockRecorder) TempArenaInfo(installPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TempArenaInfo", reflect.TypeOf((*MockLocalStorage)(nil).TempArenaInfo), installPath)
}

// UserConfig mocks base method.
func (m *MockLocalStorage) UserConfig() (data.UserConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfig")
	ret0, _ := ret[0].(data.UserConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserConfig indicates an expected call of UserConfig.
func (mr *MockLocalStorageMockRecorder) UserConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfig", reflect.TypeOf((*MockLocalStorage)(nil).UserConfig))
}
