// Code generated by MockGen. DO NOT EDIT.
// Source: local_storage.go
//
// Generated by this command:
//
//	mockgen -source=local_storage.go -destination ../mock/local_storage.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	data "wfs/internal/data"

	gomock "go.uber.org/mock/gomock"
)

// MockLocalStorage is a mock of LocalStorage interface.
type MockLocalStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLocalStorageMockRecorder
	isgomock struct{}
}

// MockLocalStorageMockRecorder is the mock recorder for MockLocalStorage.
type MockLocalStorageMockRecorder struct {
	mock *MockLocalStorage
}

// NewMockLocalStorage creates a new mock instance.
func NewMockLocalStorage(ctrl *gomock.Controller) *MockLocalStorage {
	mock := &MockLocalStorage{ctrl: ctrl}
	mock.recorder = &MockLocalStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalStorage) EXPECT() *MockLocalStorageMockRecorder {
	return m.recorder
}

// BattleArenas mocks base method.
func (m *MockLocalStorage) BattleArenas() (map[int]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BattleArenas")
	ret0, _ := ret[0].(map[int]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BattleArenas indicates an expected call of BattleArenas.
func (mr *MockLocalStorageMockRecorder) BattleArenas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BattleArenas", reflect.TypeOf((*MockLocalStorage)(nil).BattleArenas))
}

// BattleTypes mocks base method.
func (m *MockLocalStorage) BattleTypes() (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BattleTypes")
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BattleTypes indicates an expected call of BattleTypes.
func (mr *MockLocalStorageMockRecorder) BattleTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BattleTypes", reflect.TypeOf((*MockLocalStorage)(nil).BattleTypes))
}

// OwnIGN mocks base method.
func (m *MockLocalStorage) OwnIGN() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnIGN")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OwnIGN indicates an expected call of OwnIGN.
func (mr *MockLocalStorageMockRecorder) OwnIGN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnIGN", reflect.TypeOf((*MockLocalStorage)(nil).OwnIGN))
}

// SetBattleArenas mocks base method.
func (m *MockLocalStorage) SetBattleArenas(arg0 map[int]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBattleArenas", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBattleArenas indicates an expected call of SetBattleArenas.
func (mr *MockLocalStorageMockRecorder) SetBattleArenas(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBattleArenas", reflect.TypeOf((*MockLocalStorage)(nil).SetBattleArenas), arg0)
}

// SetBattleTypes mocks base method.
func (m *MockLocalStorage) SetBattleTypes(arg0 map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBattleTypes", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBattleTypes indicates an expected call of SetBattleTypes.
func (mr *MockLocalStorageMockRecorder) SetBattleTypes(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBattleTypes", reflect.TypeOf((*MockLocalStorage)(nil).SetBattleTypes), arg0)
}

// SetOwnIGN mocks base method.
func (m *MockLocalStorage) SetOwnIGN(ign string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOwnIGN", ign)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOwnIGN indicates an expected call of SetOwnIGN.
func (mr *MockLocalStorageMockRecorder) SetOwnIGN(ign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOwnIGN", reflect.TypeOf((*MockLocalStorage)(nil).SetOwnIGN), ign)
}

// SetUserConfig mocks base method.
func (m *MockLocalStorage) SetUserConfig(arg0 data.UserConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserConfig indicates an expected call of SetUserConfig.
func (mr *MockLocalStorageMockRecorder) SetUserConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserConfig", reflect.TypeOf((*MockLocalStorage)(nil).SetUserConfig), arg0)
}

// SetWarships mocks base method.
func (m *MockLocalStorage) SetWarships(arg0 data.Warships) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWarships", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWarships indicates an expected call of SetWarships.
func (mr *MockLocalStorageMockRecorder) SetWarships(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWarships", reflect.TypeOf((*MockLocalStorage)(nil).SetWarships), arg0)
}

// TempArenaInfo mocks base method.
func (m *MockLocalStorage) TempArenaInfo(installPath string) (data.TempArenaInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TempArenaInfo", installPath)
	ret0, _ := ret[0].(data.TempArenaInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TempArenaInfo indicates an expected call of TempArenaInfo.
func (mr *MockLocalStorageMockRecorder) TempArenaInfo(installPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TempArenaInfo", reflect.TypeOf((*MockLocalStorage)(nil).TempArenaInfo), installPath)
}

// UserConfig mocks base method.
func (m *MockLocalStorage) UserConfig() (data.UserConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserConfig")
	ret0, _ := ret[0].(data.UserConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserConfig indicates an expected call of UserConfig.
func (mr *MockLocalStorageMockRecorder) UserConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserConfig", reflect.TypeOf((*MockLocalStorage)(nil).UserConfig))
}

// Warships mocks base method.
func (m *MockLocalStorage) Warships() (data.Warships, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Warships")
	ret0, _ := ret[0].(data.Warships)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Warships indicates an expected call of Warships.
func (mr *MockLocalStorageMockRecorder) Warships() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warships", reflect.TypeOf((*MockLocalStorage)(nil).Warships))
}
