// Code generated by MockGen. DO NOT EDIT.
// Source: numbers_api_client.go
//
// Generated by this command:
//
//	mockgen -source=numbers_api_client.go -destination ../mock/numbers_api_client.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	data "wfs/internal/data"

	gomock "go.uber.org/mock/gomock"
)

// MockNumbersApiClient is a mock of NumbersApiClient interface.
type MockNumbersApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockNumbersApiClientMockRecorder
	isgomock struct{}
}

// MockNumbersApiClientMockRecorder is the mock recorder for MockNumbersApiClient.
type MockNumbersApiClientMockRecorder struct {
	mock *MockNumbersApiClient
}

// NewMockNumbersApiClient creates a new mock instance.
func NewMockNumbersApiClient(ctrl *gomock.Controller) *MockNumbersApiClient {
	mock := &MockNumbersApiClient{ctrl: ctrl}
	mock.recorder = &MockNumbersApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNumbersApiClient) EXPECT() *MockNumbersApiClientMockRecorder {
	return m.recorder
}

// ExpectedStats mocks base method.
func (m *MockNumbersApiClient) ExpectedStats() (data.NSExpectedStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectedStats")
	ret0, _ := ret[0].(data.NSExpectedStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpectedStats indicates an expected call of ExpectedStats.
func (mr *MockNumbersApiClientMockRecorder) ExpectedStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectedStats", reflect.TypeOf((*MockNumbersApiClient)(nil).ExpectedStats))
}
