// Code generated by MockGen. DO NOT EDIT.
// Source: persistence_interface.go
//
// Generated by this command:
//
//	mockgen -source=persistence_interface.go -destination ../mock/persistence_interface.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	data "wfs/internal/data"

	gomock "go.uber.org/mock/gomock"
)

// MockPersistenceInterface is a mock of PersistenceInterface interface.
type MockPersistenceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPersistenceInterfaceMockRecorder
	isgomock struct{}
}

// MockPersistenceInterfaceMockRecorder is the mock recorder for MockPersistenceInterface.
type MockPersistenceInterfaceMockRecorder struct {
	mock *MockPersistenceInterface
}

// NewMockPersistenceInterface creates a new mock instance.
func NewMockPersistenceInterface(ctrl *gomock.Controller) *MockPersistenceInterface {
	mock := &MockPersistenceInterface{ctrl: ctrl}
	mock.recorder = &MockPersistenceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistenceInterface) EXPECT() *MockPersistenceInterfaceMockRecorder {
	return m.recorder
}

// LoadExpectedStats mocks base method.
func (m *MockPersistenceInterface) LoadExpectedStats() (data.ExpectedStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadExpectedStats")
	ret0, _ := ret[0].(data.ExpectedStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadExpectedStats indicates an expected call of LoadExpectedStats.
func (mr *MockPersistenceInterfaceMockRecorder) LoadExpectedStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadExpectedStats", reflect.TypeOf((*MockPersistenceInterface)(nil).LoadExpectedStats))
}

// LoadOwnIGN mocks base method.
func (m *MockPersistenceInterface) LoadOwnIGN() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadOwnIGN")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadOwnIGN indicates an expected call of LoadOwnIGN.
func (mr *MockPersistenceInterfaceMockRecorder) LoadOwnIGN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadOwnIGN", reflect.TypeOf((*MockPersistenceInterface)(nil).LoadOwnIGN))
}

// LoadUserConfig mocks base method.
func (m *MockPersistenceInterface) LoadUserConfig() (data.UserConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadUserConfig")
	ret0, _ := ret[0].(data.UserConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadUserConfig indicates an expected call of LoadUserConfig.
func (mr *MockPersistenceInterfaceMockRecorder) LoadUserConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadUserConfig", reflect.TypeOf((*MockPersistenceInterface)(nil).LoadUserConfig))
}

// SaveExpectedStats mocks base method.
func (m *MockPersistenceInterface) SaveExpectedStats(arg0 data.ExpectedStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveExpectedStats", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveExpectedStats indicates an expected call of SaveExpectedStats.
func (mr *MockPersistenceInterfaceMockRecorder) SaveExpectedStats(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveExpectedStats", reflect.TypeOf((*MockPersistenceInterface)(nil).SaveExpectedStats), arg0)
}

// SaveOwnIGN mocks base method.
func (m *MockPersistenceInterface) SaveOwnIGN(ign string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOwnIGN", ign)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOwnIGN indicates an expected call of SaveOwnIGN.
func (mr *MockPersistenceInterfaceMockRecorder) SaveOwnIGN(ign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOwnIGN", reflect.TypeOf((*MockPersistenceInterface)(nil).SaveOwnIGN), ign)
}

// SaveUserConfig mocks base method.
func (m *MockPersistenceInterface) SaveUserConfig(arg0 data.UserConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUserConfig indicates an expected call of SaveUserConfig.
func (mr *MockPersistenceInterfaceMockRecorder) SaveUserConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserConfig", reflect.TypeOf((*MockPersistenceInterface)(nil).SaveUserConfig), arg0)
}
