// Code generated by MockGen. DO NOT EDIT.
// Source: replay_reader.go
//
// Generated by this command:
//
//	mockgen -source=replay_reader.go -destination ../mock/replay_reader.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	data "wfs/internal/data"

	gomock "go.uber.org/mock/gomock"
)

// MockReplayReader is a mock of ReplayReader interface.
type MockReplayReader struct {
	ctrl     *gomock.Controller
	recorder *MockReplayReaderMockRecorder
	isgomock struct{}
}

// MockReplayReaderMockRecorder is the mock recorder for MockReplayReader.
type MockReplayReaderMockRecorder struct {
	mock *MockReplayReader
}

// NewMockReplayReader creates a new mock instance.
func NewMockReplayReader(ctrl *gomock.Controller) *MockReplayReader {
	mock := &MockReplayReader{ctrl: ctrl}
	mock.recorder = &MockReplayReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplayReader) EXPECT() *MockReplayReaderMockRecorder {
	return m.recorder
}

// TempArenaInfo mocks base method.
func (m *MockReplayReader) TempArenaInfo(installPath string) (data.TempArenaInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TempArenaInfo", installPath)
	ret0, _ := ret[0].(data.TempArenaInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TempArenaInfo indicates an expected call of TempArenaInfo.
func (mr *MockReplayReaderMockRecorder) TempArenaInfo(installPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TempArenaInfo", reflect.TypeOf((*MockReplayReader)(nil).TempArenaInfo), installPath)
}
