// Code generated by MockGen. DO NOT EDIT.
// Source: wargaming_api_client.go
//
// Generated by this command:
//
//	mockgen -source=wargaming_api_client.go -destination ../mock/wargaming_api_client.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	data "wfs/internal/data"

	gomock "go.uber.org/mock/gomock"
)

// MockWargamingApiClient is a mock of WargamingApiClient interface.
type MockWargamingApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockWargamingApiClientMockRecorder
	isgomock struct{}
}

// MockWargamingApiClientMockRecorder is the mock recorder for MockWargamingApiClient.
type MockWargamingApiClientMockRecorder struct {
	mock *MockWargamingApiClient
}

// NewMockWargamingApiClient creates a new mock instance.
func NewMockWargamingApiClient(ctrl *gomock.Controller) *MockWargamingApiClient {
	mock := &MockWargamingApiClient{ctrl: ctrl}
	mock.recorder = &MockWargamingApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWargamingApiClient) EXPECT() *MockWargamingApiClientMockRecorder {
	return m.recorder
}

// AccountInfo mocks base method.
func (m *MockWargamingApiClient) AccountInfo(accountIDs []int) (data.WGAccountInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountInfo", accountIDs)
	ret0, _ := ret[0].(data.WGAccountInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountInfo indicates an expected call of AccountInfo.
func (mr *MockWargamingApiClientMockRecorder) AccountInfo(accountIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountInfo", reflect.TypeOf((*MockWargamingApiClient)(nil).AccountInfo), accountIDs)
}

// AccountList mocks base method.
func (m *MockWargamingApiClient) AccountList(accountNames []string) (data.WGAccountList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountList", accountNames)
	ret0, _ := ret[0].(data.WGAccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountList indicates an expected call of AccountList.
func (mr *MockWargamingApiClientMockRecorder) AccountList(accountNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountList", reflect.TypeOf((*MockWargamingApiClient)(nil).AccountList), accountNames)
}

// BattleArenas mocks base method.
func (m *MockWargamingApiClient) BattleArenas() (data.WGBattleArenas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BattleArenas")
	ret0, _ := ret[0].(data.WGBattleArenas)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BattleArenas indicates an expected call of BattleArenas.
func (mr *MockWargamingApiClientMockRecorder) BattleArenas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BattleArenas", reflect.TypeOf((*MockWargamingApiClient)(nil).BattleArenas))
}

// BattleTypes mocks base method.
func (m *MockWargamingApiClient) BattleTypes() (data.WGBattleTypes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BattleTypes")
	ret0, _ := ret[0].(data.WGBattleTypes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BattleTypes indicates an expected call of BattleTypes.
func (mr *MockWargamingApiClientMockRecorder) BattleTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BattleTypes", reflect.TypeOf((*MockWargamingApiClient)(nil).BattleTypes))
}

// ClansAccountInfo mocks base method.
func (m *MockWargamingApiClient) ClansAccountInfo(accountIDs []int) (data.WGClansAccountInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClansAccountInfo", accountIDs)
	ret0, _ := ret[0].(data.WGClansAccountInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClansAccountInfo indicates an expected call of ClansAccountInfo.
func (mr *MockWargamingApiClientMockRecorder) ClansAccountInfo(accountIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClansAccountInfo", reflect.TypeOf((*MockWargamingApiClient)(nil).ClansAccountInfo), accountIDs)
}

// ClansInfo mocks base method.
func (m *MockWargamingApiClient) ClansInfo(clanIDs []int) (data.WGClansInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClansInfo", clanIDs)
	ret0, _ := ret[0].(data.WGClansInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClansInfo indicates an expected call of ClansInfo.
func (mr *MockWargamingApiClientMockRecorder) ClansInfo(clanIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClansInfo", reflect.TypeOf((*MockWargamingApiClient)(nil).ClansInfo), clanIDs)
}

// EncycShips mocks base method.
func (m *MockWargamingApiClient) EncycShips(pageNo int) (data.WGEncycShips, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncycShips", pageNo)
	ret0, _ := ret[0].(data.WGEncycShips)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncycShips indicates an expected call of EncycShips.
func (mr *MockWargamingApiClientMockRecorder) EncycShips(pageNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncycShips", reflect.TypeOf((*MockWargamingApiClient)(nil).EncycShips), pageNo)
}

// ShipsBadges mocks base method.
func (m *MockWargamingApiClient) ShipsBadges(accountID int) (data.WGShipsBadges, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShipsBadges", accountID)
	ret0, _ := ret[0].(data.WGShipsBadges)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShipsBadges indicates an expected call of ShipsBadges.
func (mr *MockWargamingApiClientMockRecorder) ShipsBadges(accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShipsBadges", reflect.TypeOf((*MockWargamingApiClient)(nil).ShipsBadges), accountID)
}

// ShipsStats mocks base method.
func (m *MockWargamingApiClient) ShipsStats(accountID int) (data.WGShipsStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShipsStats", accountID)
	ret0, _ := ret[0].(data.WGShipsStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShipsStats indicates an expected call of ShipsStats.
func (mr *MockWargamingApiClientMockRecorder) ShipsStats(accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShipsStats", reflect.TypeOf((*MockWargamingApiClient)(nil).ShipsStats), accountID)
}
